spring:
  application:
    name: forgex-auth
  profiles:
    active: ${FORGEX_PROFILE:dev}
  datasource:
    type: com.baomidou.dynamic.datasource.DynamicRoutingDataSource
  output:
    ansi:
      enabled: always
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n"
  charset:
    console: UTF-8
  level:
    root: INFO
  group: {}
server:
  port: ${FORGEX_AUTH_PORT:9001}

