spring:
  config:
    import:
      - nacos:common.yml
      - nacos:datasource-forgex-test.yml
      - nacos:redis.yml
      - nacos:rocketmq.yml
      - nacos:sa-token.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${FORGEX_NACOS_ADDR:127.0.0.1:8848}
        namespace: test
        group: DEFAULT_GROUP
      config:
        server-addr: ${FORGEX_NACOS_ADDR:127.0.0.1:8848}
        namespace: test
        group: DEFAULT_GROUP
        file-extension: yml

logging:
  level:
    com.forgex.report: info
    com.pig4wei.ureport2: warn
    org.jeecgframework.jimureport: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: ${FORGEX_LOG_DIR:logs}/forgex-report/forgex-report.log
    max-size: 100MB
    max-history: 30

ureport:
  debug: false
  cache-enabled: true
  cache-time: 600

jmreport:
  mode: 1
  preview-cross: false
