-- Patch remaining tables after unsigned zerofill issue
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
USE `forgex_admin`;
START TRANSACTION;

ALTER TABLE `sys_user_tenant` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id??';

DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_user_tenant`;
CREATE TEMPORARY TABLE `tmp_map_sys_user_tenant` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_user_tenant` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY user_id, tenant_id, id) FROM `sys_user_tenant`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_user_role`;
CREATE TEMPORARY TABLE `tmp_map_sys_user_role` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_user_role` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY tenant_id, user_id, role_id, id) FROM `sys_user_role`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_user_menu_favorite`;
CREATE TEMPORARY TABLE `tmp_map_sys_user_menu_favorite` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_user_menu_favorite` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY tenant_id, user_id, order_num, id) FROM `sys_user_menu_favorite`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_role_menu`;
CREATE TEMPORARY TABLE `tmp_map_sys_role_menu` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_role_menu` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY tenant_id, role_id, menu_id, id) FROM `sys_role_menu`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_user_menu_common`;
CREATE TEMPORARY TABLE `tmp_map_sys_user_menu_common` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_user_menu_common` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY tenant_id, user_id, visit_count DESC, id) FROM `sys_user_menu_common`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_user_menu_open_count`;
CREATE TEMPORARY TABLE `tmp_map_sys_user_menu_open_count` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_user_menu_open_count` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY tenant_id, user_id, last_open_at, id) FROM `sys_user_menu_open_count`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_android_version_upload_task`;
CREATE TEMPORARY TABLE `tmp_map_sys_android_version_upload_task` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_android_version_upload_task` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY id) FROM `sys_android_version_upload_task`;
DROP TEMPORARY TABLE IF EXISTS `tmp_map_sys_tenant_menu_copy_rule`;
CREATE TEMPORARY TABLE `tmp_map_sys_tenant_menu_copy_rule` (old_id BIGINT NOT NULL PRIMARY KEY, new_id BIGINT NOT NULL UNIQUE) ENGINE=MEMORY;
INSERT INTO `tmp_map_sys_tenant_menu_copy_rule` (old_id, new_id) SELECT id, ROW_NUMBER() OVER (ORDER BY tenant_type, perm_prefix, id) FROM `sys_tenant_menu_copy_rule`;

-- Reassign primary keys using high temporary IDs to support unsigned columns.
UPDATE `sys_user_tenant` t JOIN `tmp_map_sys_user_tenant` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_user_tenant` t JOIN `tmp_map_sys_user_tenant` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_user_role` t JOIN `tmp_map_sys_user_role` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_user_role` t JOIN `tmp_map_sys_user_role` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_user_menu_favorite` t JOIN `tmp_map_sys_user_menu_favorite` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_user_menu_favorite` t JOIN `tmp_map_sys_user_menu_favorite` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_role_menu` t JOIN `tmp_map_sys_role_menu` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_role_menu` t JOIN `tmp_map_sys_role_menu` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_user_menu_common` t JOIN `tmp_map_sys_user_menu_common` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_user_menu_common` t JOIN `tmp_map_sys_user_menu_common` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_user_menu_open_count` t JOIN `tmp_map_sys_user_menu_open_count` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_user_menu_open_count` t JOIN `tmp_map_sys_user_menu_open_count` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_android_version_upload_task` t JOIN `tmp_map_sys_android_version_upload_task` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_android_version_upload_task` t JOIN `tmp_map_sys_android_version_upload_task` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;
UPDATE `sys_tenant_menu_copy_rule` t JOIN `tmp_map_sys_tenant_menu_copy_rule` m ON t.`id` = m.old_id SET t.`id` = 9000000000000000000 + m.new_id;
UPDATE `sys_tenant_menu_copy_rule` t JOIN `tmp_map_sys_tenant_menu_copy_rule` m ON t.`id` = 9000000000000000000 + m.new_id SET t.`id` = m.new_id;

-- Normalize auto_increment counters.
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_user_tenant`);
SET @sql := CONCAT('ALTER TABLE `sys_user_tenant` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_user_role`);
SET @sql := CONCAT('ALTER TABLE `sys_user_role` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_user_menu_favorite`);
SET @sql := CONCAT('ALTER TABLE `sys_user_menu_favorite` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_role_menu`);
SET @sql := CONCAT('ALTER TABLE `sys_role_menu` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_user_menu_common`);
SET @sql := CONCAT('ALTER TABLE `sys_user_menu_common` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_user_menu_open_count`);
SET @sql := CONCAT('ALTER TABLE `sys_user_menu_open_count` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_android_version_upload_task`);
SET @sql := CONCAT('ALTER TABLE `sys_android_version_upload_task` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_tenant_menu_copy_rule`);
SET @sql := CONCAT('ALTER TABLE `sys_tenant_menu_copy_rule` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_tenant`);
SET @sql := CONCAT('ALTER TABLE `sys_tenant` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_user`);
SET @sql := CONCAT('ALTER TABLE `sys_user` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_role`);
SET @sql := CONCAT('ALTER TABLE `sys_role` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_menu`);
SET @sql := CONCAT('ALTER TABLE `sys_menu` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_dict`);
SET @sql := CONCAT('ALTER TABLE `sys_dict` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @next_ai := (SELECT COALESCE(MAX(`id`), 0) + 1 FROM `sys_permission`);
SET @sql := CONCAT('ALTER TABLE `sys_permission` AUTO_INCREMENT = ', @next_ai);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
SELECT TABLE_NAME, TABLE_ROWS, AUTO_INCREMENT, TABLE_COMMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA='forgex_admin' AND TABLE_NAME IN ('sys_tenant','sys_user','sys_role','sys_menu','sys_dict','sys_permission','sys_user_tenant','sys_user_role','sys_user_menu_favorite','sys_role_menu','sys_user_menu_common','sys_user_menu_open_count','sys_android_version_upload_task','sys_tenant_menu_copy_rule') ORDER BY TABLE_NAME;
