spring:
  application:
    name: forgex-gateway
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthContributorAutoConfiguration
  config:
    import:
      - nacos:common.yml
      - nacos:redis.yml
      - nacos:sa-token.yml
  # 配置WebFlux文件上传大小限制
  codec:
    multipart:
      max-in-memory-size: 209715200
      max-parts: 10
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yml
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                exposed-headers:
                  - Content-Disposition
                allow-credentials: true
                max-age: 3600
          routes:
            - id: api-auth
              uri: lb://forgex-auth
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
            - id: api-sys
              uri: lb://forgex-sys
              predicates:
                - Path=/api/sys/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
                - name: CircuitBreaker
                  args:
                    name: api-sys
                    fallbackUri: forward:/fallback/sys
            - id: api-files
              uri: lb://forgex-sys
              predicates:
                - Path=/api/files/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                - name: CircuitBreaker
                  args:
                    name: api-files
                    fallbackUri: forward:/fallback/files
            - id: api-wf
              uri: lb://forgex-workflow
              predicates:
                - Path=/api/wf/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                - name: CircuitBreaker
                  args:
                    name: api-wf
                    fallbackUri: forward:/fallback/sys
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
  main:
    web-application-type: reactive
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n"
  charset:
    console: UTF-8
server:
  port: 9000
