<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.forgex</groupId><artifactId>Forgex_Backend</artifactId><version>1.0.0</version></parent>
    <artifactId>Forgex_Common_Crypto</artifactId><name>Forgex_Common_Crypto</name>
    <dependencies>
        <dependency><groupId>com.forgex</groupId><artifactId>Forgex_Common_Core</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.bouncycastle</groupId><artifactId>bcprov-jdk18on</artifactId></dependency>
        <dependency><groupId>cn.hutool</groupId><artifactId>hutool-all</artifactId></dependency>
        <dependency><groupId>com.baomidou</groupId><artifactId>mybatis-plus-core</artifactId><version>${mybatis-plus.version}</version></dependency>
        <dependency><groupId>org.springframework</groupId><artifactId>spring-context</artifactId></dependency>
        <dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId></dependency>
        <dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><scope>provided</scope></dependency>
    </dependencies>
</project>
