package com.forgex.basic.enums;

import com.forgex.common.i18n.I18nPrompt;
import lombok.Getter;

/**
 * 基础模块提示枚举。
 *
 * @author ForGexTeam
 * @version 1.0.0
 */
@Getter
public enum BasicPromptEnum implements I18nPrompt {
    MATERIAL_NOT_FOUND("MATERIAL_NOT_FOUND", "物料不存在"),
    MATERIAL_CODE_EXISTS("MATERIAL_CODE_EXISTS", "物料编码已存在"),
    MATERIAL_EXTEND_NOT_FOUND("MATERIAL_EXTEND_NOT_FOUND", "扩展信息不存在"),
    MODULE_CODE_REQUIRED("MODULE_CODE_REQUIRED", "模块编码不能为空"),
    MATERIAL_EXTEND_CONFIG_NOT_FOUND("MATERIAL_EXTEND_CONFIG_NOT_FOUND", "扩展配置不存在"),
    MODULE_CODE_EMPTY("MODULE_CODE_EMPTY", "模块编码不能为空"),
    FIELD_NAME_EXISTS("FIELD_NAME_EXISTS", "模块 [{0}] 下字段 [{1}] 已存在"),

    BARCODE_GENERATE_FAILED("BARCODE_GENERATE_FAILED", "生成条码号失败，请稍后重试"),
    BARCODE_NOT_FOUND("BARCODE_NOT_FOUND", "条码不存在"),
    BARCODE_NOT_FOUND_WITH_NO("BARCODE_NOT_FOUND_WITH_NO", "条码不存在 {0}"),
    BARCODE_STATUS_INVALID("BARCODE_STATUS_INVALID", "无效的条码状态 {0}"),
    BARCODE_EXPIRED("BARCODE_EXPIRED", "条码已失效"),
    BARCODE_VOIDED("BARCODE_VOIDED", "条码已作废"),

    LABEL_TEMPLATE_NOT_FOUND("LABEL_TEMPLATE_NOT_FOUND", "模板不存在"),
    LABEL_TEMPLATE_NOT_FOUND_WITH_ID("LABEL_TEMPLATE_NOT_FOUND_WITH_ID", "模板不存在，ID: {0}"),
    LABEL_TEMPLATE_ACCESS_DENIED("LABEL_TEMPLATE_ACCESS_DENIED", "无权访问该模板，模板租户ID: {0}，当前租户ID: {1}"),
    LABEL_TEMPLATE_CODE_EXISTS("LABEL_TEMPLATE_CODE_EXISTS", "模板编码已存在：{0}"),
    LABEL_TEMPLATE_TYPE_MISMATCH("LABEL_TEMPLATE_TYPE_MISMATCH", "模板类型不匹配"),
    LABEL_TEMPLATE_DISABLED("LABEL_TEMPLATE_DISABLED", "模板已禁用，无法打印"),
    LABEL_TEMPLATE_AVAILABLE_NOT_FOUND("LABEL_TEMPLATE_AVAILABLE_NOT_FOUND", "未找到可用模板"),
    LABEL_TEMPLATE_CONFIG_MISSING("LABEL_TEMPLATE_CONFIG_MISSING", "未找到可用模板，请检查模板配置"),
    LABEL_BINDING_TYPE_INVALID("LABEL_BINDING_TYPE_INVALID", "无效的绑定类型 {0}"),
    LABEL_BINDING_EXISTS("LABEL_BINDING_EXISTS", "该绑定关系已存在"),
    LABEL_BINDING_NOT_FOUND("LABEL_BINDING_NOT_FOUND", "绑定关系不存在"),
    LABEL_PREVIEW_LIMIT_EXCEEDED("LABEL_PREVIEW_LIMIT_EXCEEDED", "预览最多支持 10 张"),
    LABEL_PRINT_COUNT_REQUIRED("LABEL_PRINT_COUNT_REQUIRED", "打印张数必须大于 0"),
    LABEL_PRINT_COUNT_LIMIT_EXCEEDED("LABEL_PRINT_COUNT_LIMIT_EXCEEDED", "单次打印不能超过 1000 张"),
    LABEL_PRINT_DATA_INCOMPLETE("LABEL_PRINT_DATA_INCOMPLETE", "数据不完整，缺少字段: {0}"),
    LABEL_PRINT_RECORD_NOT_FOUND("LABEL_PRINT_RECORD_NOT_FOUND", "打印记录不存在"),

    SUPPLIER_CODE_EXISTS("SUPPLIER_CODE_EXISTS", "供应商编码已存在"),
    SUPPLIER_NOT_FOUND("SUPPLIER_NOT_FOUND", "供应商不存在"),
    SUPPLIER_CODE_IMMUTABLE("SUPPLIER_CODE_IMMUTABLE", "供应商编码创建后不可修改"),
    SUPPLIER_LINKED_TENANT_DELETE_FORBIDDEN("SUPPLIER_LINKED_TENANT_DELETE_FORBIDDEN", "已关联租户的供应商不允许删除"),
    SUPPLIER_LINKED_TENANT_NOT_FOUND("SUPPLIER_LINKED_TENANT_NOT_FOUND", "供应商已存在关联租户编号，但系统租户不存在"),
    SUPPLIER_TENANT_CODE_OCCUPIED("SUPPLIER_TENANT_CODE_OCCUPIED", "租户编码已被其它供应商占用"),
    SUPPLIER_TENANT_CREATE_FAILED("SUPPLIER_TENANT_CREATE_FAILED", "创建供应商租户失败"),
    SUPPLIER_ID_REQUIRED("SUPPLIER_ID_REQUIRED", "供应商 ID 不能为空"),
    SUPPLIER_REVIEW_NONE_FORBIDDEN("SUPPLIER_REVIEW_NONE_FORBIDDEN", "无需审查状态不允许发起审查"),
    SUPPLIER_REVIEW_PROCESSING_FORBIDDEN("SUPPLIER_REVIEW_PROCESSING_FORBIDDEN", "审查中的供应商不允许再次发起审查"),
    SUPPLIER_REVIEW_ONLY_PENDING("SUPPLIER_REVIEW_ONLY_PENDING", "仅未审查供应商允许发起审查"),
    SUPPLIER_REVIEW_START_FAILED("SUPPLIER_REVIEW_START_FAILED", "发起供应商资质审查失败"),
    SUPPLIER_REVIEW_CALLBACK_SUPPLIER_ID_MISSING("SUPPLIER_REVIEW_CALLBACK_SUPPLIER_ID_MISSING", "供应商审查回调缺少 supplierId"),
    SUPPLIER_THIRD_PARTY_SYNC_FAILED("SUPPLIER_THIRD_PARTY_SYNC_FAILED", "供应商第三方同步失败"),
    SUPPLIER_IMPORT_FILE_REQUIRED("SUPPLIER_IMPORT_FILE_REQUIRED", "导入文件不能为空"),
    SUPPLIER_PARAM_REQUIRED("SUPPLIER_PARAM_REQUIRED", "供应商参数不能为空"),
    SUPPLIER_CODE_REQUIRED("SUPPLIER_CODE_REQUIRED", "供应商编码不能为空"),
    SUPPLIER_FULL_NAME_REQUIRED("SUPPLIER_FULL_NAME_REQUIRED", "供应商全称不能为空"),
    SUPPLIER_DATA_REQUIRED("SUPPLIER_DATA_REQUIRED", "供应商数据不能为空"),
    SUPPLIER_DEFAULT_TAX_RATE_RANGE("SUPPLIER_DEFAULT_TAX_RATE_RANGE", "默认税率必须在 0 到 100 之间"),
    SUPPLIER_FIELD_VALUE_INVALID("SUPPLIER_FIELD_VALUE_INVALID", "{0}值非法：{1}"),
    SUPPLIER_REVIEW_FORM_SERIALIZE_FAILED("SUPPLIER_REVIEW_FORM_SERIALIZE_FAILED", "供应商审查表单序列化失败"),
    SUPPLIER_REVIEW_CALLBACK_FORM_PARSE_FAILED("SUPPLIER_REVIEW_CALLBACK_FORM_PARSE_FAILED", "供应商审查回调表单解析失败"),
    SUPPLIER_IMPORT_MAIN_SHEET_MISSING("SUPPLIER_IMPORT_MAIN_SHEET_MISSING", "导入文件缺少主表 sheet"),
    SUPPLIER_IMPORT_MAIN_CODE_DUPLICATED("SUPPLIER_IMPORT_MAIN_CODE_DUPLICATED", "主表供应商编码重复：{0}"),
    SUPPLIER_IMPORT_MAIN_SHEET_EMPTY("SUPPLIER_IMPORT_MAIN_SHEET_EMPTY", "导入文件主表不能为空"),
    SUPPLIER_IMPORT_ORPHAN_CODE("SUPPLIER_IMPORT_ORPHAN_CODE", "{0} sheet 第 {1} 行存在孤儿供应商编码：{2}"),
    SUPPLIER_DATE_FORMAT_INVALID("SUPPLIER_DATE_FORMAT_INVALID", "非法日期格式：{0}"),

    CUSTOMER_CODE_EXISTS("CUSTOMER_CODE_EXISTS", "客户编码已存在"),
    CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND", "客户不存在"),
    CUSTOMER_CODE_IMMUTABLE("CUSTOMER_CODE_IMMUTABLE", "客户编码创建后不可修改"),
    CUSTOMER_LINKED_TENANT_DELETE_FORBIDDEN("CUSTOMER_LINKED_TENANT_DELETE_FORBIDDEN", "已关联租户的客户不允许删除"),
    CUSTOMER_LINKED_TENANT_NOT_FOUND("CUSTOMER_LINKED_TENANT_NOT_FOUND", "客户已存在关联租户编号，但系统租户不存在"),
    CUSTOMER_TENANT_CODE_OCCUPIED("CUSTOMER_TENANT_CODE_OCCUPIED", "租户编码已被其它客户占用"),
    CUSTOMER_TENANT_CREATE_FAILED("CUSTOMER_TENANT_CREATE_FAILED", "创建客户租户失败"),
    CUSTOMER_ID_REQUIRED("CUSTOMER_ID_REQUIRED", "客户 ID 不能为空"),
    CUSTOMER_PARAM_REQUIRED("CUSTOMER_PARAM_REQUIRED", "客户参数不能为空"),
    CUSTOMER_CODE_REQUIRED("CUSTOMER_CODE_REQUIRED", "客户编码不能为空"),
    CUSTOMER_FULL_NAME_REQUIRED("CUSTOMER_FULL_NAME_REQUIRED", "客户全称不能为空"),
    CUSTOMER_APPROVAL_PROCESSING_FORBIDDEN("CUSTOMER_APPROVAL_PROCESSING_FORBIDDEN", "审批中的客户不允许再次发起审批"),
    CUSTOMER_APPROVAL_START_FAILED("CUSTOMER_APPROVAL_START_FAILED", "发起客户审批失败"),
    CUSTOMER_APPROVAL_FORM_SERIALIZE_FAILED("CUSTOMER_APPROVAL_FORM_SERIALIZE_FAILED", "客户审批表单序列化失败"),
    CUSTOMER_APPROVAL_CALLBACK_CUSTOMER_ID_MISSING("CUSTOMER_APPROVAL_CALLBACK_CUSTOMER_ID_MISSING", "客户审批回调缺少 customerId"),
    CUSTOMER_APPROVAL_CALLBACK_FORM_PARSE_FAILED("CUSTOMER_APPROVAL_CALLBACK_FORM_PARSE_FAILED", "客户审批回调表单解析失败"),

    CURRENCY_CODE_EXISTS("CURRENCY_CODE_EXISTS", "币种编码已存在"),
    CURRENCY_NOT_FOUND("CURRENCY_NOT_FOUND", "币种不存在"),
    CURRENCY_CODE_IMMUTABLE("CURRENCY_CODE_IMMUTABLE", "币种编码创建后不可修改"),
    CURRENCY_CODE_INVALID("CURRENCY_CODE_INVALID", "币种编码必须为 ISO 4217 三位大写字母"),
    CURRENCY_BASE_ONLY_ONE("CURRENCY_BASE_ONLY_ONE", "本位币仅允许设置一个"),
    CURRENCY_DISABLED_FOR_RATE("CURRENCY_DISABLED_FOR_RATE", "禁用币种不能维护汇率"),
    RATE_TYPE_CODE_EXISTS("RATE_TYPE_CODE_EXISTS", "汇率类型编码已存在"),
    RATE_TYPE_NOT_FOUND("RATE_TYPE_NOT_FOUND", "汇率类型不存在"),
    RATE_TYPE_CODE_IMMUTABLE("RATE_TYPE_CODE_IMMUTABLE", "汇率类型编码创建后不可修改"),
    EXCHANGE_RATE_NOT_FOUND("EXCHANGE_RATE_NOT_FOUND", "汇率记录不存在"),
    EXCHANGE_RATE_PAIR_INVALID("EXCHANGE_RATE_PAIR_INVALID", "源币种和目标币种不能相同"),
    EXCHANGE_RATE_DATE_INVALID("EXCHANGE_RATE_DATE_INVALID", "汇率失效日期不能早于生效日期"),
    EXCHANGE_RATE_OVERLAP("EXCHANGE_RATE_OVERLAP", "同币种对、汇率类型和组织下存在重叠生效汇率"),
    EXCHANGE_RATE_APPROVAL_PROCESSING_FORBIDDEN("EXCHANGE_RATE_APPROVAL_PROCESSING_FORBIDDEN", "审批中的汇率不允许再次发起审批"),
    EXCHANGE_RATE_APPROVAL_START_FAILED("EXCHANGE_RATE_APPROVAL_START_FAILED", "发起汇率审批失败"),
    EXCHANGE_RATE_CALLBACK_RATE_ID_MISSING("EXCHANGE_RATE_CALLBACK_RATE_ID_MISSING", "汇率审批回调缺少 rateId"),
    EXCHANGE_RATE_CALLBACK_FORM_PARSE_FAILED("EXCHANGE_RATE_CALLBACK_FORM_PARSE_FAILED", "汇率审批回调表单解析失败"),

    UNIT_TYPE_CODE_EXISTS("UNIT_TYPE_CODE_EXISTS", "计量单位类型编码已存在"),
    UNIT_TYPE_NOT_FOUND("UNIT_TYPE_NOT_FOUND", "计量单位类型不存在"),
    UNIT_TYPE_HAS_CHILDREN("UNIT_TYPE_HAS_CHILDREN", "计量单位类型下存在子类型，禁止删除"),
    UNIT_TYPE_HAS_UNITS("UNIT_TYPE_HAS_UNITS", "计量单位类型下存在计量单位，禁止删除"),
    UNIT_CODE_EXISTS("UNIT_CODE_EXISTS", "同类型下计量单位编码已存在"),
    UNIT_NOT_FOUND("UNIT_NOT_FOUND", "计量单位不存在"),
    UNIT_HAS_CONVERSION("UNIT_HAS_CONVERSION", "计量单位存在换算关系，禁止删除"),
    UNIT_CONVERSION_TARGET_INVALID("UNIT_CONVERSION_TARGET_INVALID", "目标计量单位必须与源单位属于同一类型"),
    UNIT_CONVERSION_RELATION_EXISTS("UNIT_CONVERSION_RELATION_EXISTS", "计量单位换算关系已存在"),
    UNIT_CONVERSION_RELATION_NOT_FOUND("UNIT_CONVERSION_RELATION_NOT_FOUND", "计量单位换算关系不存在"),
    UNIT_CONVERT_PARAM_INVALID("UNIT_CONVERT_PARAM_INVALID", "计量单位换算参数不完整"),
    UNIT_CONVERT_FIELD_NOT_FOUND("UNIT_CONVERT_FIELD_NOT_FOUND", "计量单位换算字段不存在：{0}"),
    UNIT_CONVERT_FIELD_NOT_NUMBER("UNIT_CONVERT_FIELD_NOT_NUMBER", "计量单位换算字段不是数字：{0}");

    private final String promptCode;
    private final String defaultTemplate;

    BasicPromptEnum(String promptCode, String defaultTemplate) {
        this.promptCode = promptCode;
        this.defaultTemplate = defaultTemplate;
    }

    @Override
    public String getModule() {
        return "basic";
    }
}
