spring:
  config:
    import:
      - nacos:common.yml
      - nacos:datasource-forgex-dev.yml
      - nacos:redis.yml
      - nacos:rocketmq.yml
      - nacos:sa-token.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${FORGEX_NACOS_ADDR:127.0.0.1:8848}
        namespace: dev
        group: DEFAULT_GROUP
      config:
        server-addr: ${FORGEX_NACOS_ADDR:127.0.0.1:8848}
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yml

logging:
  level:
    com.forgex.report: debug

ureport:
  debug: true
  cache-enabled: false

jmreport:
  mode: 0
  preview-cross: true

server:
  port: ${FORGEX_REPORT_PORT:9006}
