package com.forgex.workflow.enums;

import com.forgex.common.i18n.I18nPrompt;
import lombok.Getter;

/**
 * 工作流模块提示枚举
 * <p>
 * 约定：{@link #promptCode} 需与表 {@code fx_i18n_message.prompt_code} 保持一致，
 * 由 {@code module + promptCode} 唯一定位一条国际化文案记录。
 * </p>
 * <p>主要功能：</p>
 * <ul>
 *   <li>审批发起相关提示消息</li>
 *   <li>审批处理相关提示消息</li>
 *   <li>任务配置相关提示消息</li>
 *   <li>回调处理相关提示消息</li>
 * </ul>
 *
 * @author Forgex
 * @version 1.0.0
 * @see com.forgex.common.service.i18n.I18nMessageService
 * @see com.forgex.common.web.RMessageI18nAdvice
 */
@Getter
public enum WorkflowPromptEnum implements I18nPrompt {
    // ========== 审批发起 ==========
    WF_START_SUCCESS("WF_START_SUCCESS", "发起审批成功"),
    WF_START_FAILED("WF_START_FAILED", "发起审批失败"),
    
    // ========== 审批处理 ==========
    WF_APPROVE_SUCCESS("WF_APPROVE_SUCCESS", "审批同意成功"),
    WF_APPROVE_FAILED("WF_APPROVE_FAILED", "审批通过失败"),
    WF_REJECT_SUCCESS("WF_REJECT_SUCCESS", "审批驳回成功"),
    WF_REJECT_FAILED("WF_REJECT_FAILED", "审批驳回失败"),
    WF_CANCEL_SUCCESS("WF_CANCEL_SUCCESS", "审批取消成功"),
    WF_CANCEL_FAILED("WF_CANCEL_FAILED", "审批取消失败"),
    
    // ========== 任务相关 ==========
    WF_TASK_NOT_FOUND("WF_TASK_NOT_FOUND", "审批任务不存在"),
    WF_ALREADY_PROCESSED("WF_ALREADY_PROCESSED", "该任务已被处理"),
    WF_NO_PERMISSION("WF_NO_PERMISSION", "无权处理该任务"),
    WF_NOT_INITIATOR("WF_NOT_INITIATOR", "只有发起人可以执行此操作"),
    
    // ========== 任务配置 ==========
    WF_TASK_CONFIG_NOT_FOUND("WF_TASK_CONFIG_NOT_FOUND", "审批任务配置不存在"),
    WF_TASK_CONFIG_EXISTS("WF_TASK_CONFIG_EXISTS", "审批任务配置已存在"),
    WF_TASK_CONFIG_CREATE_SUCCESS("WF_TASK_CONFIG_CREATE_SUCCESS", "审批任务配置创建成功"),
    WF_TASK_CONFIG_UPDATE_SUCCESS("WF_TASK_CONFIG_UPDATE_SUCCESS", "审批任务配置更新成功"),
    WF_TASK_CONFIG_DELETE_SUCCESS("WF_TASK_CONFIG_DELETE_SUCCESS", "审批任务配置删除成功"),
    WF_TASK_CONFIG_EMPTY("WF_TASK_CONFIG_EMPTY", "任务配置不能为空"),
    WF_CUSTOM_FORM_PATH_REQUIRED("WF_CUSTOM_FORM_PATH_REQUIRED", "自定义表单模式必须配置表单路径"),
    WF_LOW_CODE_FORM_CONTENT_REQUIRED("WF_LOW_CODE_FORM_CONTENT_REQUIRED", "低代码表单内容不能为空"),
    WF_LOW_CODE_FORM_INVALID_JSON("WF_LOW_CODE_FORM_INVALID_JSON", "低代码表单配置必须是合法 JSON"),
    WF_LOW_CODE_FIELD_KEY_DUPLICATE("WF_LOW_CODE_FIELD_KEY_DUPLICATE", "低代码表单字段标识不能重复: {0}"),

    // ========== 节点相关 ==========
    WF_NODE_NOT_FOUND("WF_NODE_NOT_FOUND", "审批节点不存在"),
    WF_NODE_CONFIG_INVALID("WF_NODE_CONFIG_INVALID", "审批节点配置无效"),
    
    // ========== 回调处理 ==========
    WF_CALLBACK_SUCCESS("WF_CALLBACK_SUCCESS", "回调处理成功"),
    WF_CALLBACK_FAILED("WF_CALLBACK_FAILED", "回调处理失败"),
    
    // ========== 审批执行相关 (WfExecutionServiceImpl) ==========
    WF_EXECUTION_NOT_FOUND("WF_EXECUTION_NOT_FOUND", "审批执行记录不存在"),
    WF_EXECUTION_NOT_RUNNING("WF_EXECUTION_NOT_RUNNING", "当前审批不在审批中状态"),
    WF_CURRENT_NODE_NOT_FOUND("WF_CURRENT_NODE_NOT_FOUND", "当前审批节点不存在"),
    WF_USER_NO_PENDING_TASK("WF_USER_NO_PENDING_TASK", "当前用户没有该审批节点的待办任务"),
    WF_EXECUTION_DETAIL_NOT_FOUND("WF_EXECUTION_DETAIL_NOT_FOUND", "当前审批节点执行明细不存在"),
    WF_INSTANCE_NOT_FOUND_OR_NO_PERMISSION("WF_INSTANCE_NOT_FOUND_OR_NO_PERMISSION", "当前审批实例不存在或无权处理"),
    WF_INSTANCE_ALREADY_PROCESSED("WF_INSTANCE_ALREADY_PROCESSED", "审批实例已处理"),
    WF_DELEGATOR_AND_DELEGATEE_REQUIRED("WF_DELEGATOR_AND_DELEGATEE_REQUIRED", "委托人与受托人不能为空"),
    WF_DELEGATEE_SAME_AS_DELEGATOR("WF_DELEGATEE_SAME_AS_DELEGATOR", "受托人不能与委托人相同"),
    WF_FORM_CONTENT_REQUIRED("WF_FORM_CONTENT_REQUIRED", "审批表单内容不能为空"),
    WF_FORM_CONTENT_INVALID_JSON("WF_FORM_CONTENT_INVALID_JSON", "审批表单内容必须是合法 JSON"),
    WF_TASK_DISABLED("WF_TASK_DISABLED", "审批任务已被禁用"),
    WF_LOW_CODE_FORM_NOT_CONFIGURED("WF_LOW_CODE_FORM_NOT_CONFIGURED", "当前审批流程未配置低代码表单"),
    WF_ONLY_INITIATOR_CAN_CANCEL("WF_ONLY_INITIATOR_CAN_CANCEL", "仅发起人本人可以撤销审批"),
    WF_TRANSFER_TARGET_SAME_AS_CURRENT("WF_TRANSFER_TARGET_SAME_AS_CURRENT", "转交目标审批人不能与当前审批人相同"),
    WF_USER_NO_PERMISSION_TRANSFER("WF_USER_NO_PERMISSION_TRANSFER", "当前用户无权转交该审批实例"),
    WF_USER_NO_PERMISSION_ADD_SIGN("WF_USER_NO_PERMISSION_ADD_SIGN", "当前用户无权加签该审批实例"),
    WF_APPROVAL_INSTANCE_REQUIRED("WF_APPROVAL_INSTANCE_REQUIRED", "审批实例不能为空"),
    WF_EXECUTION_IDS_REQUIRED("WF_EXECUTION_IDS_REQUIRED", "审批执行记录不存在"),
    
    // ========== 引擎相关 (WfEngineServiceImpl) ==========
    WF_TASK_CONFIG_NOT_FOUND_FOR_INIT("WF_TASK_CONFIG_NOT_FOUND_FOR_INIT", "审批任务配置不存在"),
    WF_EXECUTION_NOT_FOUND_FOR_INIT("WF_EXECUTION_NOT_FOUND_FOR_INIT", "审批执行记录不存在"),
    WF_START_NODE_NOT_CONFIGURED("WF_START_NODE_NOT_CONFIGURED", "审批任务未配置开始节点"),
    WF_NEXT_NODE_NOT_FOUND("WF_NEXT_NODE_NOT_FOUND", "下一节点不存在"),
    WF_NODE_APPROVER_RESOLVE_EMPTY("WF_NODE_APPROVER_RESOLVE_EMPTY", "审批节点未匹配到有效审批人，请检查角色、岗位或部门配置"),
    
    // ========== 任务配置相关 (WfTaskConfigServiceImpl) ==========
    WF_TASK_CODE_REQUIRED("WF_TASK_CODE_REQUIRED", "任务编码不能为空"),
    WF_TASK_CODE_EXISTS("WF_TASK_CODE_EXISTS", "任务编码已存在"),
    WF_PUBLISHED_PROCESS_NOT_ALLOW_MODIFY_TASK_CODE("WF_PUBLISHED_PROCESS_NOT_ALLOW_MODIFY_TASK_CODE", "已发布流程不允许修改任务编码"),
    WF_DRAFT_NOT_FOUND("WF_DRAFT_NOT_FOUND", "草稿不存在"),
    WF_DRAFT_NOT_FOUND_PLEASE_SAVE_BASE_INFO("WF_DRAFT_NOT_FOUND_PLEASE_SAVE_BASE_INFO", "草稿不存在，请先保存基础信息"),
    WF_REQUEST_PARAM_REQUIRED("WF_REQUEST_PARAM_REQUIRED", "请求参数不能为空"),
    WF_TASK_IDENTIFIER_REQUIRED("WF_TASK_IDENTIFIER_REQUIRED", "任务标识不能为空"),
    WF_GRAPH_REQUIRED("WF_GRAPH_REQUIRED", "流程图不能为空"),
    WF_NODE_KEY_REQUIRED("WF_NODE_KEY_REQUIRED", "节点标识不能为空"),
    WF_NODE_KEY_DUPLICATE("WF_NODE_KEY_REQUIRED", "节点标识重复：{0}"),
    WF_NODE_TYPE_NOT_SUPPORTED("WF_NODE_TYPE_NOT_SUPPORTED", "存在不支持的节点类型"),
    WF_EDGE_MISSING_SOURCE_OR_TARGET("WF_EDGE_MISSING_SOURCE_OR_TARGET", "连线缺少起点或终点"),
    WF_EDGE_REFERENCES_NONEXISTENT_NODE("WF_EDGE_REFERENCES_NONEXISTENT_NODE", "连线引用了不存在的节点"),
    WF_NODE_SELF_LOOP_NOT_ALLOWED("WF_NODE_SELF_LOOP_NOT_ALLOWED", "节点不允许自循环"),
    WF_EDGE_DUPLICATE("WF_EDGE_DUPLICATE", "存在重复连线"),
    WF_START_NODE_REQUIRED("WF_START_NODE_REQUIRED", "流程必须且只能有一个开始节点"),
    WF_END_NODE_REQUIRED("WF_END_NODE_REQUIRED", "流程必须且只能有一个结束节点"),
    WF_START_NODE_HAS_PREDECESSORS("WF_START_NODE_HAS_PREDECESSORS", "开始节点不能有入边"),
    WF_START_NODE_NOT_SINGLE_SUCCESSOR("WF_START_NODE_NOT_SINGLE_SUCCESSOR", "开始节点必须有且仅有一条出边"),
    WF_END_NODE_HAS_SUCCESSORS("WF_END_NODE_HAS_SUCCESSORS", "结束节点不能有出边"),
    WF_APPROVE_NODE_NOT_SINGLE_SUCCESSOR("WF_APPROVE_NODE_NOT_SINGLE_SUCCESSOR", "审批节点必须有且仅有一条出边"),
    WF_APPROVE_NODE_NOT_CONFIGURED_APPROVE_TYPE("WF_APPROVE_NODE_NOT_CONFIGURED_APPROVE_TYPE", "审批节点必须配置审批类型"),
    WF_APPROVE_NODE_NOT_CONFIGURED_APPROVER("WF_APPROVE_NODE_NOT_CONFIGURED_APPROVER", "审批节点必须配置审批人"),
    WF_BRANCH_NODE_NOT_ENOUGH_SUCCESSORS("WF_BRANCH_NODE_NOT_ENOUGH_SUCCESSORS", "条件分支节点至少需要两条出边"),
    WF_BRANCH_NODE_NOT_CONFIGURED_DEFAULT_BRANCH("WF_BRANCH_NODE_NOT_CONFIGURED_DEFAULT_BRANCH", "条件分支节点必须配置默认分支"),
    WF_BRANCH_NODE_DEFAULT_BRANCH_NOT_IN_EDGES("WF_BRANCH_NODE_DEFAULT_BRANCH_NOT_IN_EDGES", "条件分支默认去向必须存在于出边中"),
    WF_BRANCH_NODE_NOT_ENOUGH_RULES("WF_BRANCH_NODE_NOT_ENOUGH_RULES", "条件分支节点至少需要一条规则"),
    WF_BRANCH_RULE_MISSING_FIELD_KEY("WF_BRANCH_RULE_MISSING_FIELD_KEY", "条件分支规则缺少字段键"),
    WF_BRANCH_FIELD_MUST_FROM_LOW_CODE_FORM("WF_BRANCH_FIELD_MUST_FROM_LOW_CODE_FORM", "条件分支字段必须来自低代码表单定义"),
    WF_BRANCH_RULE_MISSING_OPERATOR("WF_BRANCH_RULE_MISSING_OPERATOR", "条件分支规则缺少操作符"),
    WF_BRANCH_IN_OPERATOR_MUST_BE_JSON_ARRAY("WF_BRANCH_IN_OPERATOR_MUST_BE_JSON_ARRAY", "条件分支 in 操作符的值必须是合法 JSON 数组"),
    WF_BRANCH_NUMERIC_OPERATOR_MUST_BE_NUMBER("WF_BRANCH_NUMERIC_OPERATOR_MUST_BE_NUMBER", "数值比较类条件的值必须是数字"),
    WF_BRANCH_RULE_MISSING_TARGET_NODE("WF_BRANCH_RULE_MISSING_TARGET_NODE", "条件分支规则缺少目标节点"),
    WF_BRANCH_RULE_TARGET_NODE_NOT_IN_EDGES("WF_BRANCH_RULE_TARGET_NODE_NOT_IN_EDGES", "条件分支规则目标节点必须存在于出边中"),
    WF_GRAPH_HAS_CYCLE("WF_GRAPH_HAS_CYCLE", "流程图不能存在环"),
    WF_GRAPH_HAS_ISOLATED_NODE("WF_GRAPH_HAS_ISOLATED_NODE", "流程图存在从开始节点不可达的孤立节点"),
    WF_GRAPH_NODE_CANNOT_REACH_END("WF_GRAPH_NODE_CANNOT_REACH_END", "流程图存在无法到达结束节点的节点"),
    WF_TENANT_INFO_NOT_FOUND("WF_TENANT_INFO_NOT_FOUND", "未获取到当前租户信息"),
    WF_USER_INFO_NOT_FOUND("WF_USER_INFO_NOT_FOUND", "未获取到当前登录用户信息");

    private final String promptCode;
    private final String defaultTemplate;

    WorkflowPromptEnum(String promptCode, String defaultTemplate) {
        this.promptCode = promptCode;
        this.defaultTemplate = defaultTemplate;
    }

    @Override
    public String getModule() {
        return "workflow";
    }
}
