spring:
  application:
    name: forgex-integration
  profiles:
    active: ${FORGEX_PROFILE:dev}
  datasource:
    type: com.baomidou.dynamic.datasource.DynamicRoutingDataSource
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: ${FORGEX_INTEGRATION_PORT:9007}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.forgex.integration.domain.entity
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n"
  charset:
    console: UTF-8
  level:
    root: INFO
    com.forgex.integration: DEBUG
