spring:
  config:
    import:
      - nacos:common.yml
      - nacos:datasource-forgex-integration-yanshi.yml
      - nacos:redis.yml
      - nacos:rocketmq.yml
      - nacos:sa-token.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${FORGEX_NACOS_ADDR:127.0.0.1:8848}
        namespace: yanshi
        group: DEFAULT_GROUP
      config:
        server-addr: ${FORGEX_NACOS_ADDR:127.0.0.1:8848}
        namespace: yanshi
        group: DEFAULT_GROUP
        file-extension: yml
