-- Forgex_Job 数据库初始化入口
-- 统一 SQL 源：Forgex_Doc/数据库/脚本与修复/20260513_init_forgex_job.sql
--
-- 说明：
-- 1. Job 初始化脚本需要同时初始化 forgex_job、forgex_admin、forgex_common 三个库的数据。
-- 2. 为避免部署初始化脚本和修复脚本出现两套表结构，本文件仅作为入口说明。
-- 3. 部署或本地修复时请执行：
--    source Forgex_Doc/数据库/脚本与修复/20260513_init_forgex_job.sql;
