<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.forgex</groupId>
        <artifactId>Forgex_Backend</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>forgex-admin</artifactId>
    <packaging>pom</packaging>
    <name>forgex-admin</name>
    <description>Forgex platform governance services</description>
    <modules>
        <module>forgex-admin-auth</module>
        <module>forgex-admin-sys</module>
        <module>forgex-admin-basic</module>
        <module>forgex-admin-job</module>
        <module>forgex-admin-workflow</module>
        <module>forgex-admin-integration</module>
        <module>forgex-admin-report</module>
        <module>forgex-admin-gateway</module>
    </modules>
</project>
