metadata:
- appName: ''
  dataId: common.yml
  desc: common.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: datasource-forgex-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: forgex-common.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: redis.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: rocketmq.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: sa-token.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-config.yaml
  group: FORGEX_GROUP
  type: yaml
- appName: ''
  dataId: captcha.yaml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: lidao-common.yaml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: datasource-forgex-integration-dev.yml
  group: DEFAULT_GROUP
  type: yaml
